name: lite_dialer
description: A lightweight calling dialer for low-end Android devices.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_phone_direct_caller: ^2.1.1

flutter:
  uses-material-design: true
